name: build aio-mariadb

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: "cto4"
          password: ${{ secrets.PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: ./Dockerfile.mariadb
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            cto4/aio:mariadb
            cto4/aio:1.0.0-mariadb